#!/bin/bash


if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi


if [ "$ARCH" = "i586" ]; then
  SLKCA="Linux-x86"
  KERNH="-smp"
elif [ "$ARCH" = "i686" ]; then
   SLKCA="Linux-x86"
   KERNH="-smp"
elif [ "$ARCH" = "x86_64" ]; then
   SLKCA="Linux-x86_64"
   KERNH=""
else
   SLKCA="Linux-x86_64"
fi


RKERV=$(sed -n 3p /boot/config | awk '{print($3)}')


if [ -f /lib/modules/$RKERV/kernel/drivers/video/nvidia.ko ]; then
	echo NVida latest installed 
	exit
fi
cd /root

#check for multilib
if [ -f  /etc/profile.d/32dev.sh ]; then
NVC=".run"
else
NVC="-no-compat32.run"
fi

# This is nividia's latest stable
filename=latest.txt

#use till Nvidia fixes repo
#curl -O https://github.com/Drakeo/nvidia-update/raw/master/latest.txt 
curl -O  https://download.nvidia.com/XFree86/$SLKCA/$filename  #put back after Nvidia fixes repo

# 2 digit ending for nvidia 
GETNV=$(cat $filename |head -c -5 |tail -c -33)
RUNNV=$(cat $filename |tail -c -31|head -c -5)
# 3 digit ending for nvidia 
GETNV2=$(cat $filename |head -c -5 |tail -c -36)
RUNNV2=$(cat $filename |tail -c -32|head -c -5)


#wget -c  https://download.nvidia.com/XFree86/$SLKCA/$GETNV
URL=https://download.nvidia.com/XFree86/$SLKCA/$GETNV$NVC
if curl --output /dev/null --silent --fail -r 0-0 "$URL"; then
curl -C - -O https://download.nvidia.com/XFree86/$SLKCA/$GETNV$NVC
BRNV=$RUNNV$NVC
else
curl -C - -O https://download.nvidia.com/XFree86/$SLKCA/$GETNV2$NVC
BRNV=$RUNNV2$NVC 
  fi

echo down loading $BRNV
#remove for rerun
rm  $filename

#install NVIDIA kernel version for kernel upgrades
if [ -f /usr/bin/nvidia-settings ]; then
 echo your choice to save settings
 sleep 3 
 sh $BRNV -a  -k $RKERV
else
 echo  This is a new install jsut restart your Machine
sh $BRNV -a -q -X -k $RKERV
fi
