#!/bin/bash


if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi


if [ "$ARCH" = "i586" ]; then
  SLKCA="Linux-x86"
  KERNH="-smp"
elif [ "$ARCH" = "i686" ]; then
   SLKCA="Linux-x86"
   KERNH="-smp"
elif [ "$ARCH" = "x86_64" ]; then
   SLKCA="Linux-x86_64"
   KERNH=""
else
   SLKCA="Linux-x86_64"
fi

RKERV=$(uname -r)

if [ -f /lib/modules/$RKERV/kernel/drivers/video/nvidia.ko ]; then
	echo NVida latest installed 
	exit
else
cd /root

# This is nividia's latest stable
filename=latest.txt

#use till Nvidia fixes repo
wget https://github.com/Drakeo/nvidia-update/raw/master/latest.txt
#wget  https://download.nvidia.com/XFree86/$SLKCA/$filename #put back after Nvidia fixes repo

# 2 digit ending for nvidia 
GETNV=$(sed "s/\(.\{7\}\).\{0\}//" "${filename}")
RUNNV=$(sed "s/\(.\{14\}\).\{0\}//" "${filename}")
# 3 digit ending for nvidia 
GETNV2=$(sed "s/\(.\{8\}\).\{0\}//" "${filename}")
RUNNV2=$(sed "s/\(.\{16\}\).\{0\}//" "${filename}")


#wget -c  https://download.nvidia.com/XFree86/$SLKCA/$GETNV
URL=https://download.nvidia.com/XFree86/$SLKCA/$GETNV
if wget --spider $URL 2>/dev/null; then
wget -c  https://download.nvidia.com/XFree86/$SLKCA/$GETNV
BRNV=$RUNNV
else
wget -c  https://download.nvidia.com/XFree86/$SLKCA/$GETNV2
BRNV=$RUNNV2
  fi
fi
echo down loading $BRNV
#remove for rerun
rm  $filename

#install NVIDIA kernel version for kernel upgrades
sh $BRNV -a -q -X

